(import (scheme base))
(import (scheme small))
(import (chibi))
(import (srfi 1))
(import (srfi 26))
(import (srfi 95))
(import (srfi 115))
(import (utils))

(define INPUT (readlines "../src/in/in2.txt"))

(define (solve1 line)
    (case (string-ref line 0)
        ((#\A) (case (string-ref line 2)
            ((#\X) 4)
            ((#\Y) 8)
            ((#\Z) 3)))
        ((#\B) (case (string-ref line 2)
            ((#\X) 1)
            ((#\Y) 5)
            ((#\Z) 9)))
        ((#\C) (case (string-ref line 2)
            ((#\X) 7)
            ((#\Y) 2)
            ((#\Z) 6)))))

(define (solve2 line)
    (case (string-ref line 0)
        ((#\A) (case (string-ref line 2)
            ((#\X) 3)
            ((#\Y) 4)
            ((#\Z) 8)))
        ((#\B) (case (string-ref line 2)
            ((#\X) 1)
            ((#\Y) 5)
            ((#\Z) 9)))
        ((#\C) (case (string-ref line 2)
            ((#\X) 2)
            ((#\Y) 6)
            ((#\Z) 7)))))

(println "Answer #1:")
(->> INPUT
    (map solve1)
    (fold + 0)
    println)

(println "Answer #2:")
(->> INPUT
    (map solve2)
    (fold + 0)
    println)

